---
title: "Pushoverr Stocks"
author: "Christian Kruse"
date: "`r Sys.Date()`"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
options(scipen=999)
```

# Pushoverr Stocks

```{r}

if (!require(pacman)) { install.packages("pacman") }
install.packages('quantmod')
library(quantmod)
pacman::p_load(pushoverr,
               TTR,
               dplyr,
               tidyr,
               lubridate,
               scales,
               httr,
               ggplot2,
               fredr,
               rPref,
               glue,
               data.table)

```


```{r warning=FALSE,message=FALSE,include=FALSE}
readRenviron(path = "Renviron.site")
fredr::fredr_set_key(key = Sys.getenv("FREDAPIKEY"))
pushoverr::set_pushover_app(token = Sys.getenv("PUSHOVER_APPKEY"))
pushoverr::set_pushover_user(user = Sys.getenv("PUSHOVER_USERKEY"))

```

```{r}
num_stocks = 350
```


```{r}

query_yahoo = function(ticker) {
  getSymbols(ticker, env = NULL) %>% 
  as.data.frame(.) %>% 
  dplyr::mutate(Date=row.names(.)) %>% 
  dplyr::mutate(Date=gsub("X","",Date)) %>% 
  dplyr::mutate(Date=ymd(Date)) %>% 
  dplyr::select(c(7,1,4,3,2)) %>% 
  setNames(.,c("Date","Value","Open","Low","High")) %>% 
  na.omit() %>% 
  mutate(greenRed=ifelse(Open-Value>0,
                         "Red",
                         "Green")) %>% 
  dplyr::mutate(ticker=ticker) %>% 
  relocate(ticker) #%>% 
  # dplyr::mutate(SMA_180=TTR::SMA(x = Value,n = 365.25*0.5)) %>% 
  # dplyr::mutate(SMA_365=TTR::SMA(x = Value,n = 365.25*1)) %>% 
  # dplyr::mutate(SMA_730=TTR::SMA(x = Value,n = 365.25*2))
}
```

```{r }

add_fomc_meeting_dates = function() {
  geom_vline(xintercept = c(ymd("2022-06-15"),
                            ymd("2022-07-27"),
                            ymd("2022-09-21"),
                            ymd("2022-11-02"),
                            ymd("2022-12-14"),
                            ymd("2023-02-01"),
                            ymd("2023-03-15"),
                            ymd("2023-05-03"),
                            ymd("2023-06-14"),
                            ymd("2023-07-26"),
                            ymd("2023-09-20"),
                            ymd("2023-11-01"),
                            ymd("2023-12-13")),linetype=2,color="#eb493a")
}
```

```{r}

sector_industry_file = file.info(list.files(pattern = "nasdaq_screener",full.names = T)) %>% 
  arrange(desc(mtime)) %>% 
  slice(1) %>% 
  row.names(.) %>% 
  read.csv(file = .) %>% 
  dplyr::select(Symbol,Sector,Industry,Market.Cap,Volume)


# Get all symbols
df_stocks = stockSymbols() %>% 
  dplyr::select(Symbol,Name,Exchange,ETF) %>% 
  filter(Exchange %in% c("NASDAQ","NYSE"),
         ETF==FALSE) %>% 
  group_by(Symbol) %>% 
  filter(n()==1) %>% 
  ungroup() %>% 
  filter(!grepl("File Creation",Symbol)) %>% 
  filter(!grepl("AXAC-R",Symbol))%>% 
  filter(!grepl("ZCZZT",Symbol)) %>% 
  inner_join(sector_industry_file)

df_top = df_stocks %>% 
  dplyr::mutate(Market.Cap=Market.Cap/1000000000) %>% 
  arrange(desc(Market.Cap)) %>% 
  top_n(n = num_stocks,wt = Market.Cap)

# Bitcoin
symbols_coins = c("BTC-USD","DOGE-USD","ETH-USD")

# Metals
symbols_metals = c("GC-F","SI-F")

# Currency
symbols_currency = c("DKK-X","EUR-X","JPYDKK=X","SEKDKK=X","NOKDKK=X","AEDDKK=X","CADDKK=X","AUDDKK=X")

top_symbols = df_top %>% pull(Symbol)
# top_symbols = c(top_symbols,symbols_coins,symbols_metals,symbols_currency)
```

```{r}

list_stock_data = lapply(top_symbols,function(symbol) {
  query_yahoo(ticker = symbol)
})

df_stock_data = do.call("rbind",list_stock_data)


```

```{r}
df_stock_data %>% 
  group_by(ticker) %>% 
  dplyr::mutate(RSI_=TTR::RSI(Value,n = 90)) %>% 
  dplyr::mutate(RSI_scaled=scale(RSI_)) %>% 
  filter(RSI_scaled<=qnorm(0.03)) %>% 
  dplyr::mutate(Date=floor_date(Date,unit = "month")) %>% 
  group_by(Date) %>% 
  dplyr::summarize(count=n_distinct(ticker)) %>% 
  ggplot(.,aes(x=Date,y=count)) +
  geom_col()
  # geom_histogram(binwidth = 0.1)
```


```{r}
calculate_all = function(data) {
  # logger::log_info(unique(data$ticker))
  current_date = data %>% tail(1) 
  current_price = current_date %>% pull(Value)
  smas_ = unlist(lapply(seq(50,100*floor(nrow(data)/100)),function(sma_) { TTR::SMA(x = data$Value,n = sma_) %>% tail(1) }))
  current_sma = 50+which( abs(smas_ - current_price) == min(abs(smas_ - current_price) ) )
  current_rsi = TTR::RSI(price = data$Value) %>% scale(.) %>% tail(1) %>% pnorm()
  
  current_macd = data.frame( TTR::MACD(x = data$Value) )
  current_macd$diff = current_macd$macd - current_macd$signal
  current_macd_macd = scale(current_macd$macd) %>% tail(1) %>% pnorm()
  current_macd_signal = scale(current_macd$signal) %>% tail(1) %>% pnorm()
  current_macd_diff = scale(current_macd$signal - current_macd$macd) %>% tail(1) %>% pnorm()
  current_days_since_this_value = data %>% filter(Value<=current_price | Date==max(Date)) %>% tail(2) %>% pull(Date)
  current_days_since_this_value = as.numeric(current_days_since_this_value[2]-current_days_since_this_value[1])
  
  percentile_last_1_year = data %>% 
    filter(Date>=Sys.Date()-years(1)) %>% 
    dplyr::mutate(Value=scale(Value)) %>% 
    tail(1) %>% 
    pull(Value)  %>% 
    as.numeric() %>% 
    pnorm(., mean = 0, sd = 1, lower.tail = TRUE)
  percentile_last_5_year = data %>% 
    filter(Date>=Sys.Date()-years(5)) %>% 
    dplyr::mutate(Value=scale(Value)) %>% 
    tail(1) %>% 
    pull(Value)  %>% 
    as.numeric() %>% 
    pnorm(., mean = 0, sd = 1, lower.tail = TRUE)
  percentile_last_30_days = data %>% 
    filter(Date>=Sys.Date()-days(30)) %>% 
    dplyr::mutate(Value=scale(Value)) %>% 
    tail(1) %>% 
    pull(Value)  %>% 
    as.numeric() %>% 
    pnorm(., mean = 0, sd = 1, lower.tail = TRUE)
  
  lm_1_year = data %>% 
    filter(Date>=Sys.Date()-years(1)) %>% 
    lm(Value~Date,data=.)
  current_lm_1yr_rsq = summary(lm_1_year)$r.squared
  current_lm_1yr_expected = predict(lm_1_year,data.frame(Date=Sys.Date()+years(1)))/current_price-1

  lm_exp_14days = data %>% 
    filter(Date>=Sys.Date()-years(1)) %>% 
    lm(log(Value)~Date,data=.)
  current_exp_14days_rsq = summary(lm_exp_14days)$r.squared
  current_exp_14days_expected = exp(predict(lm_exp_14days,data.frame(Date=Sys.Date()+days(14))))/current_price-1
  
  current_rsi_strongbuy = unlist(lapply(seq(0,1,by=0.01),function(decr) { 
  temp_df = data
  temp_df$Value[nrow(temp_df)] = temp_df$Value[nrow(temp_df)]*(1-decr)
  TTR::RSI(price = temp_df$Value,n = 90) %>% scale() %>% tail(1) %>% pnorm()
      }))
  current_rsi_strongbuy = as.numeric((1-seq(0,1,by=0.01)[which(current_rsi_strongbuy<=0.02)][1])*current_price)
  
  current_percentile5yr_strongbuy = unlist(lapply(seq(0,1,by=0.01),function(decr) { 
          temp_df = data %>% filter(Date>=Sys.Date()-years(5))
          temp_df$Value[nrow(temp_df)] = temp_df$Value[nrow(temp_df)]*(1-decr)
          temp_df %>% 
            dplyr::mutate(Value=scale(Value)) %>% 
            tail(1) %>% 
            pull(Value)  %>% 
            as.numeric() %>% 
            pnorm(., mean = 0, sd = 1, lower.tail = TRUE)
      }))
  current_percentile5yr_strongbuy = as.numeric((1-seq(0,1,by=0.01)[which(current_percentile5yr_strongbuy<=0.02)][1])*current_price)
  
  # Rebound
  current_rebound = data %>% 
    filter(Date>=Sys.Date()-years(5)) %>% 
    dplyr::summarize(GrowthToATH=max(Value)/last(Value)-1) %>% 
    pull(GrowthToATH)
  
return(current_date %>% 
           dplyr::mutate(current_sma=current_sma,
                         current_rsi=current_rsi,
                         current_macd_diff=current_macd_diff,
                         current_days_since_this_value=current_days_since_this_value,
                         percentile_last_30_days=percentile_last_30_days,
                         percentile_last_1_year=percentile_last_1_year,
                         percentile_last_5_year=percentile_last_5_year,
                         current_exp_14days_rsq=current_exp_14days_rsq,
                         current_exp_14days_expected=current_exp_14days_expected,
                         current_lm_1yr_rsq=current_lm_1yr_rsq,
                         current_lm_1yr_expected=current_lm_1yr_expected,
                         current_rsi_strongbuy=current_rsi_strongbuy,
                         current_percentile5yr_strongbuy=current_percentile5yr_strongbuy,
                         current_rebound=current_rebound))
  
}

df_stock_data_analysed = df_stock_data %>% 
  group_by(ticker) %>% 
  arrange(ticker,Date) %>% 
  do(calculate_all(.)) %>% 
  ungroup()

df_stock_data_analysed
```

```{r}
worst_sma = df_stock_data_analysed %>% 
  arrange(desc(current_sma)) %>% 
  slice(1)
msg_worst_sma = glue("SMA: {worst_sma$ticker} ({worst_sma$current_sma})")
```


```{r}
worst_rsi = df_stock_data_analysed %>% 
  arrange((current_rsi)) %>% 
  slice(1)
msg_worst_rsi = glue("RSI: {worst_rsi$ticker} ({scales::percent(worst_rsi$current_rsi,accuracy=0.01)})")
```

```{r}
worst_macd = df_stock_data_analysed %>% 
  arrange(desc(current_macd_diff)) %>% 
  slice(1)
msg_worst_macd = glue("MACD: {worst_macd$ticker} ({scales::percent(worst_macd$current_macd_diff,accuracy=0.01)})")
```

```{r}
worst_days_since_this_value = df_stock_data_analysed %>% 
  arrange(desc(current_days_since_this_value)) %>% 
  slice(1)
msg_worst_days_since_this_value = glue("Days Since: {worst_days_since_this_value$ticker} ({worst_days_since_this_value$current_days_since_this_value})")
```

```{r}

p = high(current_exp_14days_expected) * high(current_exp_14days_rsq)
msg_best_exp = psel(df_stock_data_analysed %>% filter(current_exp_14days_expected>=0), p, top = nrow(df_stock_data_analysed %>% filter(current_exp_14days_expected>=0))) %>% 
    filter(.level %in% c(1,2)) %>% 
    dplyr::mutate(label_=glue("{ticker}: {scales::percent(current_exp_14days_expected,accuracy=1)} (R2: {scales::percent(current_exp_14days_rsq,accuracy=1)})")) %>% 
    pull(label_) %>% 
    paste(collapse="\n")

```

```{r}

p = high(current_lm_1yr_expected) * high(current_lm_1yr_rsq)
msg_best_lm = psel(df_stock_data_analysed %>% filter(current_lm_1yr_expected>=0), p, top = nrow(df_stock_data_analysed %>% filter(current_lm_1yr_expected>=0))) %>% 
    filter(.level %in% c(1,2)) %>% 
    dplyr::mutate(label_=glue("{ticker}: {scales::percent(current_lm_1yr_expected,accuracy=1)} (R2: {scales::percent(current_lm_1yr_rsq,accuracy=1)})")) %>% 
    pull(label_) %>% 
    paste(collapse="\n")
```

```{r}
best_turnaround  = df_stock_data_analysed %>% 
  filter(current_rebound>0) %>% 
  arrange(desc(current_rebound)) %>% 
  slice(1)
best_turnaround = glue("Turnaround: {best_turnaround$ticker}, {scales::percent(best_turnaround$current_rebound,accuracy=1)}")
```

# Push over

```{r}

df_buying_levels = df_stock_data_analysed %>% 
  dplyr::select(ticker,Value,current_rsi_strongbuy,current_percentile5yr_strongbuy) %>% 
  dplyr::mutate(pct_rsi = (current_rsi_strongbuy/Value)-1) %>% 
  dplyr::mutate(pct_pct = (current_percentile5yr_strongbuy/Value)-1)

bestbuy_rsi = df_buying_levels %>% 
    arrange(desc(pct_rsi)) %>% 
    top_n(10,wt = pct_rsi) %>% 
    dplyr::mutate(label_rsi=paste0(ticker,": ",scales::number(current_rsi_strongbuy,accuracy = 0.01)," ( ",scales::percent(pct_rsi,accuracy = 1)," )")) %>% 
    pull(label_rsi) %>% 
    paste(.,collapse="\n")
bestbuy_rsi = paste0("\nRSI:\n",bestbuy_rsi)

bestbuy_pci = df_buying_levels %>% 
    arrange(desc(pct_pct)) %>% 
    top_n(10,wt = pct_pct) %>% 
    dplyr::mutate(label_pct=paste0(ticker,": ",scales::number(current_rsi_strongbuy,accuracy = 0.01)," ( ",scales::percent(pct_pct,accuracy = 1)," )")) %>% 
    pull(label_pct) %>% 
    paste(.,collapse="\n")
bestbuy_pci = paste0("\nPCT:\n",bestbuy_pci)

```

```{r}

pushover_daily = paste(list(msg_worst_sma,msg_worst_rsi,msg_worst_macd,msg_worst_days_since_this_value,"\nEXP:",msg_best_exp,"\nLM:",msg_best_lm,best_turnaround,bestbuy_rsi,bestbuy_pci),collapse="\n")
pushoverr::pushover(pushover_daily)
```



